#!/usr/bin/env bash
set -e

cd "$(git rev-parse --show-toplevel)"

if [[ -s "${HOME}/.nvm/nvm.sh" && -f .nvmrc ]]; then
  # Git does not load the shell profile, so pick up the repo's Node.
  # shellcheck disable=SC1091
  . "${HOME}/.nvm/nvm.sh"
  nvm use --silent
fi

npm test
